org: mubashirsiddiqui
app: testing
service: peractice-serverless-http
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  region: us-east-1

functions:
  api:
    handler: index.handler
    events:
      - httpApi: "*"
